name: Build & Release

on:
  push:
    # Pattern matched against refs/tags
    tags:
      - '*'

env:
  mavenCentralUsername: ${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALUSERNAME }}
  mavenCentralPassword: ${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALPASSWORD }}
  signingInMemoryKey: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEY }}
  signingInMemoryKeyId: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYID }}
  signingInMemoryKeyPassword: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYPASSWORD }}

jobs:
  Build:
    # Skip build if head commit contains 'skip ci'
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest
    environment: "production"
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build samples
        run: ./gradlew :sample:assemble

  Upload2Maven:
    environment: "production"

    needs: Build

    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Upload library
        run: |
          ./gradlew :AlbyWidget:publishAllPublicationsToMavenCentralRepository --no-configuration-cache
          ./gradlew :AlbyWidget:closeAndReleaseRepository --no-configuration-cache
