name: Build & Release

on:
  push:
    # Pattern matched against refs/tags
    tags:
      - '*'

jobs:
  Build:
    # Skip build if head commit contains 'skip ci'
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest
    environment: "production"
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build samples
        run: |
          ./gradlew :sample:assemble \
            -PmavenCentralUsername=${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALUSERNAME }} \
            -PmavenCentralPassword=${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALPASSWORD }} \
            -PsigningInMemoryKey=${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEY }} \
            -PsigningInMemoryKeyId=${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYID }} \
            -PsigningInMemoryKeyPassword=${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYPASSWORD }}

  Upload2Maven:
    environment: "production"

    needs: Build

    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Upload library
        run: |
          ./gradlew :AlbyWidget:publishAllPublicationsToMavenCentralRepository \
            -PmavenCentralUsername=${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALUSERNAME }} \
            -PmavenCentralPassword=${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALPASSWORD }} \
            -PsigningInMemoryKey=${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEY }} \
            -PsigningInMemoryKeyId=${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYID }} \
            -PsigningInMemoryKeyPassword=${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYPASSWORD }} \
            --no-configuration-cache
          ./gradlew :AlbyWidget:closeAndReleaseRepository \
            -PmavenCentralUsername=${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALUSERNAME }} \
            -PmavenCentralPassword=${{ secrets.ORG_GRADLE_PROJECT_MAVENCENTRALPASSWORD }} \
            -PsigningInMemoryKey=${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEY }} \
            -PsigningInMemoryKeyId=${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYID }} \
            -PsigningInMemoryKeyPassword=${{ secrets.ORG_GRADLE_PROJECT_SIGNINGINMEMORYKEYPASSWORD }} \
            --no-configuration-cache
